### ISSUE TITLE
[BUG] Brewing Stand does not work

### ISSUE THREAD

**Issue by ipad54** [XenoServers/TableSpoon#17]
**Describe the bug**
Brewing Stand does not work

**To Reproduce**
1. Go to Server
2. Click on Brewing Stand
3. Try to put a bottle of water in his slot
4. You won’t be able to put it

**Comment by MonoAdrian23** [comment]
Netherwarts too

**Comment by Xenophilicy** [comment]
Brewing stands are disabled by default because they're not implemented. Please read before creating issues for things that are simply not done yet in the future 🙂
