### ISSUE TITLE
[BUG] If fireworks was on "true" crash the player when using it

### ISSUE THREAD

**Issue by UnEnanoMas** [XenoServers/TableSpoon#23]
**Describe the bug**

**To Reproduce**
1. Have fireworks activated in tablespoon
2. Use them
3. It would have given you internal server error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Xenophilicy** [comment]
What exactly is a "true" crash?

**Comment by UnEnanoMas** [comment]
I say that if you have activated the rockets in the config yml it will give you an error when using them

**Comment by Xenophilicy** [comment]
Yes, I do see that. What does `"true" crash` in the issue title refer to, though?

**Comment by Xenophilicy** [comment]
I'll look into the firework ISE issue when I have time
