### ISSUE TITLE
[BUG] Nether portal crash at join

### ISSUE THREAD

**Issue by UnEnanoMas** [XenoServers/TableSpoon#24]
If you create a portal to the Nether, and enter inside it, when it is going to do the loading animation, the server closes and restarts

**To Reproduce**
1. Create a portal to the nether
2. Enter inside the portal
3. Crash

**Expected behavior**
Let him do the charging animation, and then teleport you to the world 

(I am using the latest version to this day)

**Comment by MonoAdrian23** [comment]
Set nether in config.yml to true.
Then IT works
