### ISSUE TITLE
[BUG] The portal is not broken

### ISSUE THREAD

**Issue by UnEnanoMas** [XenoServers/TableSpoon#26]
**Describe the bug**
After you told me to set the Nether to true, I tested and it worked fine, and when I started breaking the blocks around the portal, the purple, the essence of the portal, does not disappear, even if you break all the blocks

**To Reproduce**
1. Create a portal to the Nether
2. Activate it with the lighter
3. Break the obsidian blocks
4. The portal will remain active

**Expected behavior**
That when breaking 1 block of obsidian it would break

**Screenshots**
![image](https://user-images.githubusercontent.com/63286108/93017104-5f55a700-f5c6-11ea-86f3-184db00e1885.png)

**Additional context**

**Comment by Xenophilicy** [comment]
This is already fixed in the latest build. Build the plugin from source and use that instead of the release.

**Comment by UnEnanoMas** [comment]
**This has not been fixed, I currently use the last version (in which you fixed the rockets) and the portal does not break if I break a block**
