### ISSUE TITLE
[BUG] FIREWORKS IS NOT WORKING
Error on Fireworks.php

### ISSUE THREAD

**Issue by Hoangviphb999** [XenoServers/TableSpoon#27]

**Comment by Hoangviphb999** [comment]
When players using Firework, it cause Internal Server Error.

**Comment by HyperFlareMC** [comment]
Reporting an error without context, the error, or stack trace does us no good. 

¯\_(ツ)_/¯

**Comment by MonoAdrian23** [comment]
Please Download the latest ZIP File from this Plugin.
It is fixed.

**Comment by Xenophilicy** [comment]
This issue is fixed in the latest commit. Please read the changelog, README, or commit history before creating useless issues such as this one.
