### ISSUE TITLE
[BUG] Fishing is "true" but can't fishing

### ISSUE THREAD

**Issue by namooTH** [XenoServers/TableSpoon#31]
**Describe the bug**

**To Reproduce**
1. Go to "TableSpoon"
2. Click on "config.yml"
3. Scroll down to "fishing"

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by UnEnanoMas** [comment]
I confirm this, you can not fish even if it is activated

**Comment by Xenophilicy** [comment]
Fishing is disabled by default, therefore is not currently implemented.

**Comment by UnEnanoMas** [comment]
@Xenophilicy https://github.com/benda95280/MyFish/tree/master/

Yes that can be implemented, only that it is a lot of text

**Comment by Xenophilicy** [comment]
I have no idea what that means

**Comment by UnEnanoMas** [comment]
I say that if possible, that this plugin worked well, and did its function (but it worked before, now I don't know)
