### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by MonoAdrian23** [XenoServers/TableSpoon#8]
Where can i find the phar that works?
Everyone i try to Install it says there is no Main

**Comment by HyperFlareMC** [comment]
Mono,

Currently, we haven't had any releases yet as the plugin is not stable. Once the plugin is at a stable point, we will add an official release on this GitHub page. Keep an eye out :)

**Comment by MonoAdrian23** [comment]
Thanks, i have tested the Latest on GitHub and IT works great for me.
And thanks a lot for this fork.
You make many Players much happy with this.
Sorry for my english, greetings from Germany
